/**
* Description:
* Uses: https://github.com/kevinohara80/sfdc-trigger-framework/tree/master/src/classes
* @author: {{ developerName }} (Trineo)
* @date: {{ createdDate }}
* @test:
*/
public with sharing class {{ api_name }} extends TriggerHandler {

    public override void beforeDelete() {

    }

    public override void beforeInsert() {

    }

    public override void beforeUpdate() {

    }

    public override void afterInsert() {

    }

    public override void afterUpdate() {

    }

    public override void afterUndelete() {

    }
}
